# Basic
title: bearboyxu
subtitle: 人生没有白走的路，每一步都算数... 
welcome_message: <a href="https://github.com/FantBoy/bearboy.github.io" target="_blank">该站点基于vno二次开发，点击下载源码</a>
description:  在devops的道路上，渐行渐远...
creator: <a href="http://blog.bearboyxu.cn">@bearboyxu</a>

url: "http://blog.bearboyxu.cn"

permalink: /:year/:month/:day/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue 

# The blog button should not be removed.
blog_button:
    title: 首页
    description: 访问博客首页

# Navigation buttons in the front page.
nav:
    # - {title: Another Button, description: A button, url: 'http://example.com'}
    - {title: 归档, target_blank: false, description: 访问文章归档页面, url: '/pages/archive'}
    - {title: WIKI, target_blank: true, description: 访问我的wiki站点, url: 'http://wiki.bearboyxu.cn'}
# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"
excerpt_separator:  '<!-- more -->'
# Comment
#comment:
#    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: u/2042015811 
    github: FantBoy
    #twitter: bearboyxu

    mail: bear@bearboyxu.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
